yml-vars:
  database:
    host: ${POSTGRESQL_HOST:127.0.0.1}
    port: ${POSTGRESQL_PORT:5432}
    name: ${POSTGRESQL_NAME:ma_medicals_db}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:123456}
    url: jdbc:postgresql://${yml-vars.database.host}:${yml-vars.database.port}/${yml-vars.database.name}
  app:
    port: ${APP_PORT:8090}
    baseUrl: ${APP_BASE_PREFIX:http://localhost}

server:
  port: ${yml-vars.app.port}
  baseUrl: ${yml-vars.app.baseUrl}:${yml-vars.app.port}

spring:
  ai:
    deepseek:
      model: ${DEEPSEEK_MODEL:deepseek-reason}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      api-key: ${DEEPSEEK_API_KEY:}
  application:
    name: medical-applied
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: ${yml-vars.database.url}
    driver-class-name: org.postgresql.Driver
    username: ${yml-vars.database.username}
    password: ${yml-vars.database.password}
  mail:
    port: 587
    host: smtp.gmail.com
    username: test@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    default-encoding: UTF-8
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

service:
  delay:
    processEmailsVerifiedDelay: ${CLEAR_EMAILS_VERIFIED_DELAY:1800000}
    clearViewsHistoryDelay: ${CLEAR_VIEWS_HISTORY_DELAY:3600000}
  expired:
    viewsHistoryExpiredAt: ${VIEWS_HISTORY_EXPIRED_AT:30}
    emailsVerifiedExpiredAt: ${EMAILS_VERIFIED_EXPIRED_AT:1}
  redis:
    duration: ${REDIS_TTL_DURATION:PT5H}

  token:
    signing:
      key: TEST_TEST

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    tender.ma.medicalapplied: DEBUG
