yml-vars:
  database:
    host: ${POSTGRESQL_HOST:127.0.0.1}
    port: ${POSTGRESQL_PORT:5432}
    name: ${POSTGRESQL_NAME:ma_medicals_db}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:123456}
    url: jdbc:postgresql://${yml-vars.database.host}:${yml-vars.database.port}/${yml-vars.database.name}
  app:
    port: ${APP_PORT:8090}
    baseUrl: ${APP_BASE_PREFIX:http://localhost}

server:
  port: ${yml-vars.app.port}
  baseUrl: ${yml-vars.app.baseUrl}:${yml-vars.app.port}
  ssl:
    key-store: keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:123456}
    keyStoreType: PKCS12
    keyAlias: tomcat
    enabled: ${SSL_ENABLED:false}

spring:
  ai:
    gemini:
      api-key: ${GEMINI_AI_API_KEY:ZOXs23ASQ_WiFVW3DL0hXJ7nFvhUDB1uPxCw}
      base-url: ${GEMINI_AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/models}
      action: ${GEMINI_AI_ACTION:generateContent}
      model: ${GEMINI_MODEL_NAME:gemini-flash-latest}
      url: ${spring.ai.gemini.base-url}/${spring.ai.gemini.model}:${spring.ai.gemini.action}
  application:
    name: medical-applied
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: ${yml-vars.database.url}
    driver-class-name: org.postgresql.Driver
    username: ${yml-vars.database.username}
    password: ${yml-vars.database.password}
  mail:
    port: 587
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:123456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    default-encoding: UTF-8
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

service:
  delay:
    processEmailsVerifiedDelay: ${CLEAR_EMAILS_VERIFIED_DELAY:1800000}
    clearViewsHistoryDelay: ${CLEAR_VIEWS_HISTORY_DELAY:3600000}
  expired:
    viewsHistoryExpiredAt: ${VIEWS_HISTORY_EXPIRED_AT:30}
    emailsVerifiedExpiredAt: ${EMAILS_VERIFIED_EXPIRED_AT:1}
  redis:
    duration: ${REDIS_TTL_DURATION:PT5H}

  token:
    expiration: ${TOKEN_EXPIRATION:PT5H}
    signing:
      key: ${TOKEN_SIGNING_KEY:123456}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    tender.ma.medicalapplied: DEBUG
